# Generated by Django 5.0.7 on 2025-11-02 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField(help_text='JSON object containing data fields')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Record creation timestamp')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update timestamp')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Dataset title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional description of dataset contents')),
                ('filename', models.CharField(help_text='Original filename of uploaded Excel file', max_length=255)),
                ('file_size', models.IntegerField(help_text='File size in bytes')),
                ('upload_date', models.DateTimeField(auto_now_add=True, help_text='Timestamp of upload')),
                ('record_count', models.IntegerField(default=0, help_text='Number of records in this dataset')),
                ('category', models.CharField(blank=True, help_text='Category/type of data', max_length=100)),
            ],
            options={
                'ordering': ['-upload_date'],
            },
        ),
    ]
