# Generated by Django 5.0.7 on 2025-11-02 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dataset',
            name='uploaded_by',
            field=models.ForeignKey(help_text='User who uploaded this dataset', on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datarecord',
            name='dataset',
            field=models.ForeignKey(help_text='Parent dataset', on_delete=django.db.models.deletion.CASCADE, related_name='records', to='dashboard.dataset'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['-upload_date'], name='dashboard_d_upload__e8139d_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['category'], name='dashboard_d_categor_9ed874_idx'),
        ),
        migrations.AddIndex(
            model_name='dataset',
            index=models.Index(fields=['uploaded_by'], name='dashboard_d_uploade_799497_idx'),
        ),
        migrations.AddIndex(
            model_name='datarecord',
            index=models.Index(fields=['dataset', 'created_at'], name='dashboard_d_dataset_24668a_idx'),
        ),
    ]
