# Generated by Django 5.0.7 on 2025-11-02 17:24

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('manager', 'Manager'), ('viewer', 'Viewer')], default='viewer', help_text='User role for role-based access control', max_length=20)),
                ('full_name', models.CharField(blank=True, help_text="User's full name", max_length=100)),
                ('department', models.CharField(blank=True, help_text='Department affiliation', max_length=100)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Number of consecutive failed login attempts')),
                ('account_locked_until', models.DateTimeField(blank=True, help_text='Timestamp when account lockout expires (15 minutes after 5 failures)', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last successful login', null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 수정 시각')),
                ('username_attempted', models.CharField(help_text='Username used in the attempt', max_length=150)),
                ('event_type', models.CharField(choices=[('login_success', 'Login Success'), ('login_failed', 'Login Failed'), ('logout', 'Logout'), ('token_refresh', 'Token Refresh'), ('password_change', 'Password Change'), ('account_locked', 'Account Locked')], help_text='Type of authentication event', max_length=20)),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the request')),
                ('user_agent', models.CharField(blank=True, help_text='Browser user agent string', max_length=500)),
                ('success', models.BooleanField(default=True, help_text='Whether the event was successful')),
                ('failure_reason', models.CharField(blank=True, help_text='Reason for failure (if applicable)', max_length=200)),
                ('user', models.ForeignKey(blank=True, help_text='User involved in the event (null for failed logins)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auth_logs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='생성 시각')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='마지막 수정 시각')),
                ('token', models.CharField(help_text='JWT refresh token (hashed)', max_length=500, unique=True)),
                ('reason', models.CharField(choices=[('logout', 'User Logout'), ('password_change', 'Password Changed'), ('security', 'Security Breach'), ('admin_revoke', 'Admin Revocation')], default='logout', help_text='Reason for blacklisting', max_length=20)),
                ('expires_at', models.DateTimeField(help_text='Token expiration timestamp')),
                ('user', models.ForeignKey(help_text='User who owns this token', on_delete=django.db.models.deletion.CASCADE, related_name='blacklisted_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'blacklisted_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='users_usernam_baeb4b_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role'], name='users_role_0ace22_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['user', '-created_at'], name='auth_logs_user_id_b6dc67_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['event_type', '-created_at'], name='auth_logs_event_t_09a389_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['ip_address', '-created_at'], name='auth_logs_ip_addr_c00e69_idx'),
        ),
        migrations.AddIndex(
            model_name='authlog',
            index=models.Index(fields=['-created_at'], name='auth_logs_created_19a29d_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['token'], name='blacklisted_token_d070ae_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['user', '-created_at'], name='blacklisted_user_id_5d9479_idx'),
        ),
        migrations.AddIndex(
            model_name='blacklistedtoken',
            index=models.Index(fields=['expires_at'], name='blacklisted_expires_d1bb66_idx'),
        ),
    ]
