# Generated by Django 5.0.7 on 2025-11-02 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authlog',
            name='details',
            field=models.JSONField(blank=True, help_text='Additional details about the auth event (JSON)', null=True),
        ),
    ]
